### ISSUE TITLE
Error translations

### ISSUE THREAD

**Issue by Elisardojm** [apertium/apertium-es-gl#8] opened 2019-03-27 10:15 UTC
Hi, I'm using Apertium to translate wikipedia articles with the tool Content Translation, and I have noticed two issues: 
* word "para" (preposition) is translated to "paira"
* word "una" (article) is not translated

The errors could be reviewed comparing translation of https://es.wikipedia.org/wiki/L%C3%A1mina_beta to https://gl.wikipedia.org/wiki/Usuario:Elisardojm/L%C3%A1mina_beta. 

Could anybody help to fix that, please? This issues are very important because "para" and "una" are words widely used in spanish.

**Comment by ftyers** [comment] 2019-04-04 00:22
I can't reproduce the problem with *una*:

```
$ echo "La lámina beta u hoja plegada β es una de las estructuras secundarias posibles adoptada por las proteínas." | apertium -d . es-gl
A lámina *beta ou folla encartada β é una das estruturas secundarias posibles adoptada polas proteínas.
```

The other one is:

```
$ echo "Sin embargo, Astbury no tenía los datos necesarios respecto de la geometría del enlace de los aminoácidos para construir modelos precisos, sobre todo porque no sabía entonces que el enlace peptídico era planar." | apertium -d . es-gl
Con todo, *Astbury non tiña os datos necesarios respecto da xeometría do enlace dos *aminoácidos paira construír modelos precisos, sobre todo porque non sabía entón que o enlace *peptídico era *planar.
```

I thought this was happening because of the unknown word *aminoácidos*, but I just added it and now it still gets the same result.

```
$ echo "Sin embargo, Astbury no tenía los datos necesarios respecto de la geometría del enlace de los aminoácidos para construir modelos precisos, sobre todo porque no sabía entonces que el enlace peptídico era planar." | apertium -d . es-gl
Con todo, *Astbury non tiña os datos necesarios respecto da xeometría do enlace dos aminoácidos paira construír modelos precisos, sobre todo porque non sabía entón que o enlace *peptídico era *planar.
```

It's a tagger error:

```
$ echo "Sin embargo, Astbury no tenía los datos necesarios respecto de la geometría del enlace de los aminoácidos para construir modelos precisos, sobre todo porque no sabía entonces que el enlace peptídico era planar." | apertium -d . es-gl-tagger
^Sin embargo<cnjadv>$^,<cm>$ ^*Astbury$ ^no<adv>$ ^tener<vblex><pii><p3><sg>$ ^el<det><def><m><pl>$ ^dato<n><m><pl>$ ^necesario<adj><m><pl>$ ^respecto<n><m><sg>$ ^de<pr>$ ^el<det><def><f><sg>$ ^geometría<n><f><sg>$ ^de<pr>+el<det><def><m><sg>$ ^enlazar<vblex><prs><p3><sg>$ ^de<pr>$ ^el<det><def><m><pl>$ ^aminoácido<n><m><pl>$ ^parir<vblex><prs><p3><sg>$ ^construir<vblex><inf>$ ^modelo<n><mf><pl>$ ^preciso<adj><m><pl>$^,<cm>$ ^sobre todo<adv>$ ^porque<cnjadv>$ ^no<adv>$ ^saber<vblex><pii><p3><sg>$ ^entonces<adv>$ ^que<cnjsub>$ ^el<det><def><m><sg>$ ^enlazar<vblex><prs><p3><sg>$ ^*peptídico$ ^ser<vbser><pii><p3><sg>$ ^*planar$^.<sent>$^.<sent>$
```

This could be fixed by adding CG maybe? But the pair really needs to be converted to using monolingual packages too.

**Comment by ftyers** [comment] 2019-04-04 00:27
Yep, adding the CG (see 17e901e) helps:

```
$ echo "Sin embargo, Astbury no tenía los datos necesarios respecto de la geometría del enlace de los aminoácidos para construir modelos precisos, sobre todo porque no sabía entonces que el enlace peptídico era planar." | apertium -d . es-gl
Con todo, *Astbury non tiña os datos necesarios respecto da xeometría do enlace dos aminoácidos para construír modelos precisos, sobre todo porque non sabía entón que o enlace *peptídico era *planar.
```

**Comment by Elisardojm** [comment] 2019-04-04 08:10
About "una", the translation text states: "β é **una** das estruturas", and it should be "β é **unha** das estruturas"...

**Comment by ftyers** [comment] 2019-04-04 13:39
That's working now too:

```
$ echo "La lámina beta u hoja plegada β es una de las estructuras secundarias posibles adoptada por las proteínas." | apertium -d . es-gl
A lámina *beta ou folla encartada β é unha das estruturas secundarias posibles adoptada polas proteínas.
```

**Comment by Elisardojm** [comment] 2019-04-06 09:38
Great!, but now, how are applied the changes? I have tried it here, https://www.apertium.org/index.spa.html?dir=spa-glg&q=tengo%20una%20casa%20para%20el%20perro#translation, and word "una" still isn't translated...

**Comment by Elisardojm** [comment] 2019-04-08 10:22
The translation "una" to "unha" don't works. Could somebody fix it? Thanks.

**Comment by Elisardojm** [comment] 2019-05-09 20:31
@ftyers, translation "una" to "unha" seems don't works, Could review it? I tryed to translate "Tengo una plaza en mi ayuntamiento para hacer fiestas.", and the result was "Teño >>una<< praza no meu concello para facer festas."

**Comment by ftyers** [comment] 2019-06-11 15:50
I added a CG rule in `apertium-spa` in [627c9a0](https://github.com/apertium/apertium-spa/commit/627c9a0c3467fe21d218bb187c8083cb46e327cd). It should work now:

```
$ echo "Tengo una plaza en mi ayuntamiento para hacer fiestas." | apertium -d . es-gl
Teño unha praza no meu concello para facer festas.

```

**Comment by ftyers** [comment] 2019-06-11 15:51
> Great!, but now, how are applied the changes? I have tried it here, https://www.apertium.org/index.spa.html?dir=spa-glg&q=tengo%20una%20casa%20para%20el%20perro#translation, and word "una" still isn't translated...

The changes need to be applied by either @sushain97 or @TinoDidriksen. I am not able to do it. I can fix errors in the code, but I cannot deploy them.

**Comment by TinoDidriksen** [comment] 2019-06-26 10:00
Plus a parallel build fix in https://github.com/apertium/apertium-es-gl/commit/562ca8d5235ca44ab79553d89bf645406272369e - now deployed to apertium.org.

**Closed as completed by TinoDidriksen** 2019-06-26 10:00 UTC
